version: "3"
services:

  real-estate-system-nginx:
    image: registry.cn-hangzhou.aliyuncs.com/real-estate-system/real-estate-system-nginx
    container_name: real-estate-system-nginx
    restart: always
    depends_on:
      - real-estate-system-backend
    ports:
      - 0.0.0.0:80:80
    links:
      - real-estate-system-backend
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx

  real-estate-system-postgres:
    image: postgres:10-alpine
    container_name: real-estate-system-postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=realEstateSystem
      - POSTGRES_USER=realEstateSystem
      - POSTGRES_PASSWORD=realEstateSystem
    ports:
      - 0.0.0.0:15432:5432

  real-estate-system-backend:
    image: registry.cn-hangzhou.aliyuncs.com/real-estate-system/real-estate-system-backend
    container_name: real-estate-system-backend
    restart: always
    depends_on:
      - real-estate-system-postgres
    volumes:
      # 开发环境把本地的backend挂载进docker container
      - /home/vincijoy/RealEstateDataSystem/SystemBackend:/go/src/RealEstateDataSystem
    environment:
      - POSTGRES_DB=realEstateSystem
      - POSTGRES_USER=realEstateSystem
      - POSTGRES_PASSWORD=realEstateSystem
      - POSTGRES_HOST=real-estate-system-postgres
      - POSTGRES_PORT=5432
      - JWT_KEY=hsfw1SUtV1JcokodVUh3tvOZKMujVl3j
    links:
      - real-estate-system-postgres
